### ISSUE TITLE
Memory keeps growing

### ISSUE THREAD

**Issue by llitz** [fede1024/rust-rdkafka#220] opened 2020-02-23 20:11 UTC
Not sure if this is a problem or where it is but after creating a program with FutureProducer my memory skyrocketed to 10Gb usage by having 3 FutureProducers running at the same time (otherwise I get limited to 50k EPS).

Even when running only one memory usage was at 4gb.

After chasing this a little while, I have tried running the asynchronous_processing example, and memory also grows there at least until 1GB, any idea what can be causing this?

![ss-2020-02-23-130822](https://user-images.githubusercontent.com/22463547/75119221-07f9e480-563e-11ea-99ff-c2149ca27ba7.png)

**Comment by gklijs** [comment] 2020-03-07 06:03
I think this is just page cache from c, and will be freed when needed. I did some tests before, see https://www.confluent.io/blog/getting-started-with-rust-and-kafka/ at the memory section and memory use is amazingly low, but it's measured excluding page cache. It might also be regression through.

**Comment by llitz** [comment] 2020-03-07 07:25
I don't think that's the case, I had memory usage grow all the way up to 32gb.

For now, I am limiting consumption loop to 1m entries and ending then starting it all over. This reduces how fast I can process all messages, but memory is "limited" that way.

This only happens when future producer is involved /=

**Comment by tobz** [comment] 2020-03-08 18:34
For what it's worth, I've also noticed a growing memory usage on a consumer-based application I'm working on.  I tracked it down as being related to the buffers allocated for doing gzip decompression, so maybe this is related to message _compression_ as you produce?

**Comment by llitz** [comment] 2020-03-08 18:36
I don't think so, I have compression none and the data is not compressed in the input topic either.

**Comment by gklijs** [comment] 2020-03-08 22:05
And on the broker? Because in case of compression it might be taking the property from the broker configuration.

**Comment by llitz** [comment] 2020-03-08 23:51
The data is in clear text there.

If I disable the producer the program doesn't use more than 250mb of memory to read 200k messages per second. They are around 600 bytes each, some larger, some smaller.

**Comment by Marwes** [comment] 2020-03-11 13:46
Also seeing memory leaks in an application that contains a kafka producer. Might very well be something else causing it but the existence of this issue makes kafka the most likely candidate

**Comment by benesch** [comment] 2020-03-11 14:48
Is anyone able to get a heap profile?

**Comment by Marwes** [comment] 2020-03-11 15:21
I ran the app through valgrind and didn't find anything. No idea how to get heap profiles out of production at this point.

**Comment by tobz** [comment] 2020-03-11 16:51
I can provide a macOS Instruments memory profile; getting Valgrind to work on macOS has been a pain.  Will see if I can do that unless macOS Instruments works for you.

**Comment by llitz** [comment] 2020-03-11 17:00
Valgrind doesn't show the leak.

For me, my loop does basically two things: retrieve events and sends them to the producer.

If I let it run infinitely, memory grows non-stop.
After putting a limiter on consumer with .take(1_000_000), before restarting the loop, memory is under control.

There are no leaks with valgrind. It is almost as if it requires consuming something from the future and, until that is done, memory keeps growing.

**Comment by benesch** [comment] 2020-03-17 00:27
> Will see if I can do that unless macOS Instruments works for you.

I run macOS, so that would work splendidly! Valgrind on macOS has been hopeless for the last several years, in my experience.

**Comment by benesch** [comment] 2020-03-17 00:49
Well, the issue doesn't reproduce with the simple_producer, at the very least. I changed it to produce 1MM records instead of 5. Memory usage spikes to 300MB as it constructs 1MM futures, which seems pretty reasonable, and then smoothly trends to 0 as the futures are polled, completed, and freed.

To dig in more I'd need a full reproduction, I'm afraid.

**Comment by benesch** [comment] 2020-05-14 03:20
@Marwes mentioned that they suspect their problem is in the underlying librdkafka, not the Rust wrapper. I'm going to close this in a few days unless anyone can share more information.

**Comment by llitz** [comment] 2020-05-16 13:44
I will try to reproduce the issue with a more specific code so I can post a
way to consistently reproduce it outside of my use case.

**Comment by benesch** [comment] 2020-07-10 04:50
I'm going to close this for now, since things seem to be working correctly in my tests. If you do manage to come up with a reproduction, please let me know, and I'll reopen.

**Comment by thijsc** [comment] 2021-11-26 15:06
We are seeing this happens in our production environment too. We're trying to figure out why at the moment.

**Comment by thijsc** [comment] 2021-11-26 15:49
False alarm, it was a mistake in some code we changed when upgrading. Delivery futures ended up in a vector we weren't emptying.

**Closed by thijsc** 2021-11-26 15:49 UTC
