### ISSUE TITLE
Increasing per-message latency 

### ISSUE THREAD

**Issue by VenturaDelMonte** [fede1024/rust-rdkafka#215] opened 2020-02-02 19:02 UTC
Hi all, I hope this is the right place to leave this issue and the problem I am reporting is not a duplicate.
I have a java kafka application that produces record of size 8kb at constant speed (e.g., 8 mb/s).
Each record has a generation timestamp.
Every 5k record,  i compute the latency of each record at the consuming application using the current timestamp (i.e., current timestamp - generation timestamp of a record).
I wrote a java-based consumer application that is able to sustain the producer rate, i.e., the measured latency is in the range 70-130 ms.
Now i tried to rewrite the consumer logic in Rust and I am using this library.  
What happens is that I am measuring ever-increasing latency value. The very first message that `rd_kafka_consumer_poll` returns  has already a latency of half a second. 
After 5 seconds, the average latency is already around 5 seconds. 
Note that no processing is applied on the consumer side as of now. 
Each consumer thread has its own `BaseConsumer` that it is configured to read from one partition of one topic. Consumers do not share any partition, i.e., the i-th consumer reads the i-th partition.

My current consumer config is as follows:

```
            consumer_config
                .set("group.id", "im-job")
                .set("auto.commit.interval.ms", "180000")
                .set("enable.auto.commit", "false")
                .set("auto.offset.reset", "latest")
                .set("request.timeout.ms", "305000")
                .set("fetch.wait.max.ms", "100")
                .set("acks", "0")
                .set("check.crcs", "0")
                .set("fetch.min.bytes", "8192")
                .set("queued.min.messages", "1024")
                .set("queued.max.messages.kbytes", "2097151")
                .set("max.partition.fetch.bytes", "10485760")
                .set("socket.receive.buffer.bytes", "4194304")
//                .set("statistics.interval.ms", "5000")
                .set("fetch.error.backoff.ms", "0")
//                .set("debug", "all")
                .set("bootstrap.servers", &brokers);
```

Before tuning above parameters, latency was even higher.

On the producer side, i just set  `linger.ms` to 100ms and the `batch.size` to 32kb. However, this should not be a problem as when using java applications, the latency is in check.

Overall, this is definitely odd and I was wondering if you could provide me with some assistance regarding this issue. Thank you in advance for  your time.

**Comment by benesch** [comment] 2020-02-02 19:58
It’s hard to say what’s going wrong without substantially more information.
I don’t see anything obviously wrong with your configuration, but I’m also
not an expert on Kafka configuration. You could try asking for advice
upstream (edenhill/librdkafka), since rust-rdkafka is a very
straightforward wrapper around librdkafka.

It sounds like your Rust consumer is not keeping pace with your producer.
Are you calling poll enough? Have you tried using the StreamConsumer, or
are you using the BaseConsumer directly? Are you using a release build?

I’m afraid I can’t really debug further without a full reproduction.

**Comment by VenturaDelMonte** [comment] 2020-02-04 10:42
Thank you. I will prepare an MVE and get back to you and the upstream folks so that this becomes reproducible.
I tried StreamConsumer as well as BaseConsumer. I even start the consumer in advance but the very first record is polled out with quite some delay.

**Comment by gklijs** [comment] 2020-02-19 04:10
I've done some extensive comparing of rust with the Java clients and didn't noticed this. I did saw you disabled auto commit. Maybe you are synchronously committing the offset after each consumed record?

**Comment by VenturaDelMonte** [comment] 2020-02-20 18:53
Hi @gklijs, thank you for your reply. I double checked my code but I do not have any synchronous commit of any offset - unless the default consumer is doing so under the hood. Anyway, as I mentioned in my prev update, the issue disappeared by invoking C calls on my own following the example. I will try to share my code with you asap.

**Comment by benesch** [comment] 2020-07-10 04:52
I'm going to close this out since I'm afraid it's going to be impossible to track this down without more information. If you're able to provide that information, though, happy to reopen!

**Closed by benesch** 2020-07-10 04:52 UTC
